[build]
  base    = ""
  publish = "website/build"
  command = "git backfill & yarn & wait && cd website && yarn build"
  
[context.production.environment]
  NODE_VERSION = "24"
  DOCUSAURUS_PERF_LOGGER = "true"

[context.deploy-preview.environment]
  NODE_VERSION = "24"
  PREVIEW_DEPLOY = "true"

[[headers]]
  for = "/movies.json"
    [headers.values]
    Access-Control-Allow-Origin = "*"
