name: github pages

on:
  push:
    branches:
      - production
    paths:
      - "cnwebsite/**"
      - "cndocs/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Enable Corepack
        run: corepack enable

      - name: Build
        run: |
          yarn
          cd cnwebsite
          yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cnwebsite/build
